name: Build-Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install mkdocs
      run: pip install mkdocs
    - name: build docs
      run: mkdocs build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        target_branch: docs
        build_dir: site
      env:
        GITHUB_TOKEN: ${{ secrets.pat }}
